
[connections.weather]
url = "sqlite:///db/weather.db"

[db]
original_data_table = "original_weather_data"
cleaned_data_table = "cleaned_weather_data"


[qwen]
api_key = "sk-ws-H.EDMPIEH.AJKs.MEQCIA9wEvDxYRMUlHJ0h2l-8tovq5zuReFHUfmWExH5uKcMAiAHnXAp8Z62t6nsdE7eSVv45aznoBBMnhBEu6iVi864GQ"
endpoint = "https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation"
workspace_id = "ws-sjjvm6y4yw3nlj46"

